version: '2'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - 127.0.0.1:80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        container_name: portainer
        environment:
            - VIRTUAL_HOST=portainer.local
            - VIRTUAL_PORT=9000
        volumes:
            - portainer-data:/data
            - /var/run/docker.sock:/var/run/docker.sock
volumes:
    portainer-data:
